<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JunitXml.TestLogger" Version="3.0.134" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.10" />
    <PackageReference Include="LightInject.Microsoft.Hosting" Version="1.5.3" />
    <PackageReference Include="Moq" Version="4.20.69" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="MartinCostello.Logging.XUnit" Version="0.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
  </ItemGroup>

</Project>
