<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>3.2.0-alpha.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LightInject.Microsoft.DependencyInjection" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STrain.CQS.Blazor\STrain.CQS.Blazor.csproj" />
    <ProjectReference Include="..\STrain.CQS.Extensions.DependencyInjection\STrain.CQS.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\STrain.CQS.Extensions.LightInject\STrain.CQS.Extensions.LightInject.csproj" />
  </ItemGroup>

</Project>
