<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0-rc.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="7.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STrain.CQS.Api\STrain.CQS.Api.csproj" />
    <ProjectReference Include="..\STrain.CQS\STrain.CQS.csproj" />
  </ItemGroup>

</Project>
