<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STrain.CQS.Api\STrain.CQS.Api.csproj" />
    <ProjectReference Include="..\STrain.CQS.Attributes\STrain.CQS.Attributes.csproj" />
    <ProjectReference Include="..\STrain.Eventing.Api\STrain.Eventing.Api.csproj" />
  </ItemGroup>

</Project>
