name: Continuous Integration

on:
  pull_request:
    branches: [ "develop" ]
    
jobs:
  build:
    uses: mihben/workflow-template/.github/workflows/dotnet-build.yml@main
    with:
      runs-on: windows-latest
      dotnet-version: 6.0.x
      solution: src/
      test-results: test-results
      test-runsettings: environment/test.runsettings
      artifacts: livingdoc_test
      publish-livingdoc-artifacts: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}