name: Continuous Integration

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:
    
jobs:
  build:
    uses: mihben/workflow-template/.github/workflows/dotnet-build.yml@main
    with:
      runs-on: ubuntu-latest
      dotnet-version: 6.0.x
